### PR TITLE
land:overlay: get rid of backlit button stuff

### PR DESCRIPTION
**Pull request by impulsar**
We don't have backlit buttons

### CODE REVIEW

**Comment by nichcream** [comment]
Where can I find backlight button customization? just curious.

**Comment by impulsar** [comment]
Same section as the buttons customisation in lineageOS

**Comment by impulsar** [comment]
Dk about Validus

**Comment by nichcream** [comment]
this one should go to Lineage branch..
https://review.lineageos.org/#/c/199947/

**Comment by impulsar** [comment]
Cool :)

**Pull request closed without merging**
